#ifndef OGL_PROGRAM_FACTORY_H_
#define OGL_PROGRAM_FACTORY_H_

// DREAM OS
// DreamOS/HAL/opengl/OGLProgramFractory.h
// A factory for the creation of OGLPrograms

#include "OGLProgram.h"

#include <string>
#include <map>

typedef enum {
	OGLPROGRAM_MINIMAL,
	OGLPROGRAM_MINIMAL_TEXTURE,
	OGLPROGRAM_SKYBOX,
	OGLPROGRAM_SKYBOX_SCATTER,
	OGLPROGRAM_SKYBOX_SCATTER_CUBE,
	OGLPROGRAM_BLINNPHONG,
	OGLPROGRAM_BLINNPHONG_SHADOW,
	OGLPROGRAM_BLINNPHONG_TEXTURE,
	OGLPROGRAM_BLINNPHONG_TEXTURE_SHADOW,
	OGLPROGRAM_BLINNPHONG_TEXTURE_BUMP,
	OGLPROGRAM_BLINNPHONG_TEXTURE_BUMP_DISPLACEMENT,
	OGLPROGRAM_TEXTURE_BITBLIT,
	OGLPROGRAM_FLAT,
	OGLPROGRAM_TOON,
	OGLPROGRAM_REFLECTION,
	OGLPROGRAM_REFRACTION,
	OGLPROGRAM_ENVIRONMENT,
	OGLPROGRAM_WATER,
	OGLPROGRAM_CUSTOM,
	OGLPROGRAM_SHADOW_DEPTH,
	OGLPROGRAM_REFERENCE,
	OGLPROGRAM_SCREEN_QUAD,
	OGLPROGRAM_IRRADIANCE_MAP,
	OGLPROGRAM_CUBEMAP_CONVOLUTION,

	// Deferred
	OGLPROGRAM_GBUFFER,
	OGLPROGRAM_SSAO,
	
	// Production shaders - using features from previous shaders 
	OGLPROGRAM_STANDARD, // used for models in the environment such as head and hands
	OGLPROGRAM_SCREEN_FADE,
	OGLPROGRAM_DEPTH_PEEL,
	OGLPROGRAM_BLEND_QUAD,
	OGLPROGRAM_BLUR_QUAD,
	OGLPROGRAM_UI_STAGE,
	OGLPROGRAM_BILLBOARD,

	// Testing Shader Programs
	OGLPROGRAM_DEBUG_OVERLAY,
	OGLPROGRAM_VISUALIZE_NORMALS,

	OGLPROGRAM_INVALID
} OGLPROGRAM_TYPE;

class OGLProgramFactory {
private:
	static const std::map<std::string, OGLPROGRAM_TYPE> m_OGLProgramNameType;

public:
	static ProgramNode* MakeOGLProgram(OGLPROGRAM_TYPE type, OpenGLImp *pParentImp, version versionOGL, PIPELINE_FLAGS optFlags = PIPELINE_FLAGS::NONE);
	static 	OGLPROGRAM_TYPE OGLProgramTypeFromstring(std::string strProgramName);
};

#endif // ! OGL_PROGRAM_FACTORY_H_